In [190]:
import pandas as pd
import numpy as np

url = 'https://www.sharkattackfile.net/spreadsheets/GSAF5.xls'
Shark_Attacks_df = pd.read_excel(url)

Realizamos un análisis inicial del datset para entender la estrucura y ver qué representa cada columna.

In [191]:
Shark_Attacks_df.shape

(7065, 23)

In [192]:
Shark_Attacks_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [193]:
Shark_Attacks_df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [194]:
Shark_Attacks_df.dtypes

Date               object
Year              float64
Type               object
Country            object
State              object
Location           object
Activity           object
Name               object
Sex                object
Age                object
Injury             object
Fatal Y/N          object
Time               object
Species            object
Source             object
pdf                object
href formula       object
href               object
Case Number        object
Case Number.1      object
original order    float64
Unnamed: 21        object
Unnamed: 22        object
dtype: object

In [195]:
Shark_Attacks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7065 entries, 0 to 7064
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7065 non-null   object
 1   Year            7063 non-null   float64
 2   Type            7047 non-null   object
 3   Country         7015 non-null   object
 4   State           6578 non-null   object
 5   Location        6498 non-null   object
 6   Activity        6480 non-null   object
 7   Name            6846 non-null   object
 8   Sex             6486 non-null   object
 9   Age             4070 non-null   object
 10  Injury          7030 non-null   object
 11  Fatal Y/N       6504 non-null   object
 12  Time            3538 non-null   object
 13  Species         3934 non-null   object
 14  Source          7045 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [196]:
Shark_Attacks_df.describe(include="all")

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
count,7065.0,7063.000000,7047,7015,6578,6498,6480,6846,6486,4070.0,...,3934,7045,6799,6794,6796,6798,6797,6799.000000,1,2
unique,6107.0,NaN,13,251,944,4611,1609,5785,10,251.0,...,1736,5399,6789,6784,6776,6777,6775,NaN,1,2
top,1957.0,NaN,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16.0,...,White shark,"K. McMurray, TrackingSharks.com",1907.10.16.R-HongKong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2021.07.23,2012.09.02.b,NaN,stopped here,Teramo
freq,9.0,NaN,5217,2578,1192,191,1143,679,5665,92.0,...,194,131,2,2,4,2,2,NaN,1,1
mean,NaN,1935.890981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.152081,NaN,NaN
std,NaN,270.825801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963.076319,NaN,NaN
min,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
25%,NaN,1948.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1701.500000,NaN,NaN
50%,NaN,1986.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3401.000000,NaN,NaN
75%,NaN,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5100.500000,NaN,NaN
max,NaN,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6802.000000,NaN,NaN

Comprobamos porcentaje de nulos para decidir con qué columnas seguir.

In [197]:
Shark_Attacks_df.isna().mean().sort_values(ascending=False)

Unnamed: 21       0.999858
Unnamed: 22       0.999717
Time              0.499222
Species           0.443171
Age               0.423921
Activity          0.082803
Sex               0.081953
Location          0.080255
Fatal Y/N         0.079406
State             0.068931
href formula      0.038358
href              0.038075
Case Number.1     0.037933
Case Number       0.037792
pdf               0.037650
original order    0.037650
Name              0.030998
Country           0.007077
Injury            0.004954
Source            0.002831
Type              0.002548
Year              0.000283
Date              0.000000
dtype: float64

In [198]:
#Hemos elegido estas dos hipótesis: 
# 1. Existen tipos de injury asociados a mayor probabilidad de que el ataque sea fatal (Y/N)?
# 2. Influye el tipo de actividad en la fatalidad de los ataques de tiburón en los países con más incidentes?

Revisamos duplicados

In [199]:
Shark_Attacks_df.duplicated().sum()

np.int64(0)

Seleccionamos columnas relevantes para nuestra hipótesis.

In [203]:
Shark_Attacks_df.columns = (Shark_Attacks_df.columns.str.strip().str.lower().str.replace(" ", "_"))
Shark_Attacks_df = Shark_Attacks_df.rename(columns={"fatal_y/n": "fatal"})
Shark_Attacks_df.columns

Index(['country', 'activity', 'injury', 'fatal'], dtype='object')

In [205]:
Shark_Attacks_df = Shark_Attacks_df[["country", "activity", "injury", "fatal"]]
Shark_Attacks_df.head()

,country,activity,injury,fatal
0,Australia,Surfing,puncture mark to left thumb,N
1,US Virgin Islands,Snorkeling,Left arm torn off in the attack below the elbow,Y
2,New Caledonia,Scuba Diving,Injuries to upper limbs,N
3,USA,Swimming,Taken by shark body recovered with multiple in...,Y
4,USA,Surfing,Hand Injury,N

Exploramos valores únicos

In [207]:
for col in Shark_Attacks_df:
    print(col)
    print("Valores únicos: ", Shark_Attacks_df[col].unique())
    print("Número de valores únicos: ", Shark_Attacks_df[col].nunique())

country
Valores únicos:  ['Australia' 'US Virgin Islands' 'New Caledonia' 'USA' 'French Polynesia'
 'Samoa' 'Columbia' 'Costa Rica' 'Bahamas' 'Puerto Rico' 'Spain'
 'Canary Islands' 'South Africa' 'Vanuatu' 'Jamaica' 'Israel' 'Mexico'
 'Maldives' 'Philippines' 'Turks and Caicos' 'Mozambique' 'Egypt'
 'Thailand' 'New Zealand' 'Hawaii' 'Honduras' 'Indonesia' 'Morocco'
 'Belize' 'Maldive Islands' 'Tobago' 'AUSTRALIA' 'INDIA' 'TRINIDAD'
 'BAHAMAS' 'SOUTH AFRICA' 'MEXICO' 'NEW ZEALAND' 'EGYPT' 'BELIZE'
 'PHILIPPINES' 'Coral Sea' 'SPAIN' 'PORTUGAL' 'SAMOA' 'COLOMBIA' 'ECUADOR'
 'FRENCH POLYNESIA' 'NEW CALEDONIA' 'TURKS and CaICOS' 'CUBA' 'BRAZIL'
 'SEYCHELLES' 'ARGENTINA' 'FIJI' 'MeXICO' 'ENGLAND' 'JAPAN' 'INDONESIA'
 'JAMAICA' 'MALDIVES' 'THAILAND' 'COLUMBIA' 'COSTA RICA'
 'British Overseas Territory' 'CANADA' 'JORDAN' 'ST KITTS / NEVIS'
 'ST MARTIN' 'PAPUA NEW GUINEA' 'REUNION ISLAND' 'ISRAEL' 'CHINA'
 'IRELAND' 'ITALY' 'MALAYSIA' 'LIBYA' nan 'MAURITIUS' 'SOLOMON ISLANDS'
 'ST HELENA, British overseas territory' 'COMOROS' 'REUNION'
 'UNITED KINGDOM' 'UNITED ARAB EMIRATES' 'CAPE VERDE' 'Fiji'
 'DOMINICAN REPUBLIC' 'CAYMAN ISLANDS' 'ARUBA' 'MOZAMBIQUE' 'PUERTO RICO'
 'ATLANTIC OCEAN' 'GREECE' 'ST. MARTIN' 'FRANCE' 'TRINIDAD & TOBAGO'
 'KIRIBATI' 'DIEGO GARCIA' 'TAIWAN' 'PALESTINIAN TERRITORIES' 'GUAM'
 'NIGERIA' 'TONGA' 'SCOTLAND' 'CROATIA' 'SAUDI ARABIA' 'CHILE' 'ANTIGUA'
 'KENYA' 'RUSSIA' 'TURKS & CAICOS' 'UNITED ARAB EMIRATES (UAE)' 'AZORES'
 'SOUTH KOREA' 'MALTA' 'VIETNAM' 'MADAGASCAR' 'PANAMA' 'SOMALIA' 'NEVIS'
 'BRITISH VIRGIN ISLANDS' 'NORWAY' 'SENEGAL' 'YEMEN' 'GULF OF ADEN'
 'Sierra Leone' 'ST. MAARTIN' 'GRAND CAYMAN' 'Seychelles' 'LIBERIA'
 'VANUATU' 'MEXICO ' 'HONDURAS' 'VENEZUELA' 'SRI LANKA' ' TONGA' 'URUGUAY'
 'MICRONESIA' 'CARIBBEAN SEA' 'OKINAWA' 'TANZANIA' 'MARSHALL ISLANDS'
 'EGYPT / ISRAEL' 'NORTHERN ARABIAN SEA' 'HONG KONG' 'EL SALVADOR'
 'ANGOLA' 'BERMUDA' 'MONTENEGRO' 'IRAN' 'TUNISIA' 'NAMIBIA'
 'NORTH ATLANTIC OCEAN' 'SOUTH CHINA SEA' 'BANGLADESH' 'PALAU'
 'WESTERN SAMOA' 'PACIFIC OCEAN ' 'BRITISH ISLES' 'GRENADA' 'IRAQ'
 'TURKEY' 'SINGAPORE' 'NEW BRITAIN' 'SUDAN' 'JOHNSTON ISLAND'
 'SOUTH PACIFIC OCEAN' 'NEW GUINEA' 'RED SEA' 'NORTH PACIFIC OCEAN'
 'FEDERATED STATES OF MICRONESIA' 'MID ATLANTIC OCEAN' 'ADMIRALTY ISLANDS'
 'BRITISH WEST INDIES' 'SOUTH ATLANTIC OCEAN' 'PERSIAN GULF'
 'RED SEA / INDIAN OCEAN' 'PACIFIC OCEAN' 'NORTH SEA' 'NICARAGUA '
 'MALDIVE ISLANDS' 'AMERICAN SAMOA' 'ANDAMAN / NICOBAR ISLANDAS' 'GABON'
 'MAYOTTE' 'NORTH ATLANTIC OCEAN ' 'THE BALKANS' 'SUDAN?' 'MARTINIQUE'
 'INDIAN OCEAN' 'GUATEMALA' 'NETHERLANDS ANTILLES'
 'NORTHERN MARIANA ISLANDS' 'IRAN / IRAQ' 'JAVA' 'SIERRA LEONE'
 ' PHILIPPINES' 'NICARAGUA' 'CENTRAL PACIFIC' 'SOLOMON ISLANDS / VANUATU'
 'SOUTHWEST PACIFIC OCEAN' 'BAY OF BENGAL' 'MID-PACIFC OCEAN' 'SLOVENIA'
 'CURACAO' 'ICELAND' 'ITALY / CROATIA' 'BARBADOS' 'MONACO' 'GUYANA'
 'HAITI' 'SAN DOMINGO' 'KUWAIT' 'YEMEN ' 'FALKLAND ISLANDS' 'CRETE'
 'CYPRUS' 'EGYPT ' 'WEST INDIES' 'BURMA' 'LEBANON' 'PARAGUAY'
 'BRITISH NEW GUINEA' 'CEYLON' 'OCEAN' 'GEORGIA' 'SYRIA' 'TUVALU'
 'INDIAN OCEAN?' 'GUINEA' 'ANDAMAN ISLANDS' 'EQUATORIAL GUINEA / CAMEROON'
 'COOK ISLANDS' 'TOBAGO' 'PERU' 'AFRICA' 'ALGERIA' 'Coast of AFRICA'
 'TASMAN SEA' 'GHANA' 'GREENLAND' 'MEDITERRANEAN SEA' 'SWEDEN' 'ROATAN'
 'Between PORTUGAL & INDIA' 'DJIBOUTI' 'BAHREIN' 'KOREA' 'RED SEA?'
 'ASIA?' 'CEYLON (SRI LANKA)']
Número de valores únicos:  251
activity
Valores únicos:  ['Surfing' 'Snorkeling' 'Scuba Diving' ...
 'Crew swimming alongside their anchored ship' '4 men were bathing'
 'Wreck of  large double sailing canoe']
Número de valores únicos:  1609
injury
Valores únicos:  ['puncture mark to left thumb'
 'Left arm torn off in the attack below the elbow '
 'Injuries to upper limbs' ... 'FATAL, leg stripped of flesh  '
 'FATAL, knocked overboard by tail of shark & carried off by shark '
 'FATAL. "Shark bit him in half, carrying away the lower extremities" ']
Número de valores únicos:  4179
fatal
Valores únicos:  ['N' 'Y' 'F' 'M' nan 'n' 'Nq' 'UNKNOWN' 2017 'Y x 2' ' N' 'N ' 'y']
Número de valores únicos:  12

In [213]:
for col in Shark_Attacks_df:
    Shark_Attacks_df[col] = Shark_Attacks_df[col].astype(str).str.lower().str.strip()

Shark_Attacks_df

,country,activity,injury,fatal
0,australia,surfing,puncture mark to left thumb,n
1,us virgin islands,snorkeling,left arm torn off in the attack below the elbow,y
2,new caledonia,scuba diving,injuries to upper limbs,n
3,usa,swimming,taken by shark body recovered with multiple in...,y
4,usa,surfing,hand injury,n
...,...,...,...,...
7060,australia,diving,fatal,y
7061,australia,pearl diving,fatal,y
7062,usa,swimming,fatal,y
7063,panama,nan,fatal,y
7064,ceylon (sri lanka),swimming,"fatal. ""shark bit him in half, carrying away t...",y

In [ ]:
Shark_Attacks_df["fatal"] = Shark_Attacks_df["fatal"].replace({"yes": "y", "true"})