In [1]:
import pandas as pd

In [6]:
url = 'https://www.sharkattackfile.net/spreadsheets/GSAF5.xls'

In [29]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\eliom\anaconda3\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [30]:
Shark_Attacks_df = pd.read_excel(url)

In [11]:
Shark_Attacks_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
Shark_Attacks_df.tail()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
7060,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7061,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7062,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7063,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7064,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [31]:
Shark_Attacks_df.shape

(7065, 23)

In [27]:
Shark_Attacks_df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [28]:
Shark_Attacks_df.dtypes

Date               object
Year              float64
Type               object
Country            object
State              object
Location           object
Activity           object
Name               object
Sex                object
Age                object
Injury             object
Fatal Y/N          object
Time               object
Species            object
Source             object
pdf                object
href formula       object
href               object
Case Number        object
Case Number.1      object
original order    float64
Unnamed: 21        object
Unnamed: 22        object
dtype: object

In [19]:
Shark_Attacks_df.nunique()

Date              6107
Year               261
Type                13
Country            251
State              944
Location          4611
Activity          1609
Name              5785
Sex                 10
Age                251
Injury            4179
Fatal Y/N           12
Time               469
Species           1736
Source            5399
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

In [22]:
for columna in Shark_Attacks_df.columns:
    print(f"Valores únicos por columna: {columna}")
    print(Shark_Attacks_df[columna].unique())
    print("-" *30)

Valores únicos por columna: Date
['10th January' '8th January' '3rd January ' ... '1900-1905' '1883-1889'
 '1845-1853']
------------------------------
Valores únicos por columna: Year
[2026. 2025. 2024. 2023. 2022. 2021. 2020. 2019. 2018. 2017.   nan 2016.
 2015. 2014. 2013. 2012. 2011. 2010. 2009. 2008. 2007. 2006. 2005. 2004.
 2003. 2002. 2001. 2000. 1999. 1998. 1997. 1996. 1995. 1984. 1994. 1993.
 1992. 1991. 1990. 1989. 1969. 1988. 1987. 1986. 1985. 1983. 1982. 1981.
 1980. 1979. 1978. 1977. 1976. 1975. 1974. 1973. 1972. 1971. 1970. 1968.
 1967. 1966. 1965. 1964. 1963. 1962. 1961. 1960. 1959. 1958. 1957. 1956.
 1955. 1954. 1953. 1952. 1951. 1950. 1949. 1948. 1848. 1947. 1946. 1945.
 1944. 1943. 1942. 1941. 1940. 1939. 1938. 1937. 1936. 1935. 1934. 1933.
 1932. 1931. 1930. 1929. 1928. 1927. 1926. 1925. 1924. 1923. 1922. 1921.
 1920. 1919. 1918. 1917. 1916. 1915. 1914. 1913. 1912. 1911. 1910. 1909.
 1908. 1907. 1906. 1905. 1904. 1903. 1902. 1901. 1900. 1899. 1898. 1897.
 1896. 1895. 1894. 1893. 1892. 1891. 1890. 1889. 1888. 1887. 1886. 1885.
 1884. 1883. 1882. 1881. 1880. 1879. 1878. 1877. 1876. 1875. 1874. 1873.
 1872. 1871. 1870. 1869. 1868. 1867. 1866. 1865. 1864. 1863. 1862. 1861.
 1860. 1859. 1858. 1857. 1856. 1855. 1853. 1852. 1851. 1850. 1849. 1847.
 1846. 1845. 1844. 1842. 1841. 1840. 1839. 1837. 1836. 1835. 1834. 1832.
 1831. 1830. 1829. 1828. 1827. 1826. 1825. 1823. 1822. 1819. 1818. 1817.
 1816. 1815. 1812. 1811. 1810. 1808. 1807. 1805. 1804. 1803. 1802. 1801.
 1800. 1797. 1792. 1791. 1788. 1787. 1786. 1785. 1784. 1783. 1780. 1779.
 1776. 1771. 1767. 1764. 1758. 1753. 1751. 1749. 1755. 1748. 1742. 1738.
 1733. 1723. 1721. 1703. 1700. 1642. 1691. 1640. 1638. 1637. 1617. 1595.
 1580. 1555. 1554. 1543. 1518. 1500. 1000.   77.    5.    0.]
------------------------------
Valores únicos por columna: Type
['Unprovoked' 'Provoked' 'Questionable' 'unprovoked' ' Provoked'
 'Watercraft' 'Sea Disaster' nan '?' 'Unconfirmed' 'Unverified' 'Invalid'
 'Under investigation' 'Boat']
------------------------------
Valores únicos por columna: Country
['Australia' 'US Virgin Islands' 'New Caledonia' 'USA' 'French Polynesia'
 'Samoa' 'Columbia' 'Costa Rica' 'Bahamas' 'Puerto Rico' 'Spain'
 'Canary Islands' 'South Africa' 'Vanuatu' 'Jamaica' 'Israel' 'Mexico'
 'Maldives' 'Philippines' 'Turks and Caicos' 'Mozambique' 'Egypt'
 'Thailand' 'New Zealand' 'Hawaii' 'Honduras' 'Indonesia' 'Morocco'
 'Belize' 'Maldive Islands' 'Tobago' 'AUSTRALIA' 'INDIA' 'TRINIDAD'
 'BAHAMAS' 'SOUTH AFRICA' 'MEXICO' 'NEW ZEALAND' 'EGYPT' 'BELIZE'
 'PHILIPPINES' 'Coral Sea' 'SPAIN' 'PORTUGAL' 'SAMOA' 'COLOMBIA' 'ECUADOR'
 'FRENCH POLYNESIA' 'NEW CALEDONIA' 'TURKS and CaICOS' 'CUBA' 'BRAZIL'
 'SEYCHELLES' 'ARGENTINA' 'FIJI' 'MeXICO' 'ENGLAND' 'JAPAN' 'INDONESIA'
 'JAMAICA' 'MALDIVES' 'THAILAND' 'COLUMBIA' 'COSTA RICA'
 'British Overseas Territory' 'CANADA' 'JORDAN' 'ST KITTS / NEVIS'
 'ST MARTIN' 'PAPUA NEW GUINEA' 'REUNION ISLAND' 'ISRAEL' 'CHINA'
 'IRELAND' 'ITALY' 'MALAYSIA' 'LIBYA' nan 'MAURITIUS' 'SOLOMON ISLANDS'
 'ST HELENA, British overseas territory' 'COMOROS' 'REUNION'
 'UNITED KINGDOM' 'UNITED ARAB EMIRATES' 'CAPE VERDE' 'Fiji'
 'DOMINICAN REPUBLIC' 'CAYMAN ISLANDS' 'ARUBA' 'MOZAMBIQUE' 'PUERTO RICO'
 'ATLANTIC OCEAN' 'GREECE' 'ST. MARTIN' 'FRANCE' 'TRINIDAD & TOBAGO'
 'KIRIBATI' 'DIEGO GARCIA' 'TAIWAN' 'PALESTINIAN TERRITORIES' 'GUAM'
 'NIGERIA' 'TONGA' 'SCOTLAND' 'CROATIA' 'SAUDI ARABIA' 'CHILE' 'ANTIGUA'
 'KENYA' 'RUSSIA' 'TURKS & CAICOS' 'UNITED ARAB EMIRATES (UAE)' 'AZORES'
 'SOUTH KOREA' 'MALTA' 'VIETNAM' 'MADAGASCAR' 'PANAMA' 'SOMALIA' 'NEVIS'
 'BRITISH VIRGIN ISLANDS' 'NORWAY' 'SENEGAL' 'YEMEN' 'GULF OF ADEN'
 'Sierra Leone' 'ST. MAARTIN' 'GRAND CAYMAN' 'Seychelles' 'LIBERIA'
 'VANUATU' 'MEXICO ' 'HONDURAS' 'VENEZUELA' 'SRI LANKA' ' TONGA' 'URUGUAY'
 'MICRONESIA' 'CARIBBEAN SEA' 'OKINAWA' 'TANZANIA' 'MARSHALL ISLANDS'
 'EGYPT / ISRAEL' 'NORTHERN ARABIAN SEA' 'HONG KONG' 'EL SALVADOR'
 'ANGOLA' 'BERMUDA' 'MONTENEGRO' 'IRAN' 'TUNISIA' 'NAMIBIA'
 'NORTH ATLANTIC OCEAN' 'SOUTH CHINA SEA' 'BANGLADESH' 'PALAU'
 'WESTERN SAMOA' 'PACIFIC OCEAN ' 'BRITISH ISLES' 'GRENADA' 'IRAQ'
 'TURKEY' 'SINGAPORE' 'NEW BRITAIN' 'SUDAN' 'JOHNSTON ISLAND'
 'SOUTH PACIFIC OCEAN' 'NEW GUINEA' 'RED SEA' 'NORTH PACIFIC OCEAN'
 'FEDERATED STATES OF MICRONESIA' 'MID ATLANTIC OCEAN' 'ADMIRALTY ISLANDS'
 'BRITISH WEST INDIES' 'SOUTH ATLANTIC OCEAN' 'PERSIAN GULF'
 'RED SEA / INDIAN OCEAN' 'PACIFIC OCEAN' 'NORTH SEA' 'NICARAGUA '
 'MALDIVE ISLANDS' 'AMERICAN SAMOA' 'ANDAMAN / NICOBAR ISLANDAS' 'GABON'
 'MAYOTTE' 'NORTH ATLANTIC OCEAN ' 'THE BALKANS' 'SUDAN?' 'MARTINIQUE'
 'INDIAN OCEAN' 'GUATEMALA' 'NETHERLANDS ANTILLES'
 'NORTHERN MARIANA ISLANDS' 'IRAN / IRAQ' 'JAVA' 'SIERRA LEONE'
 ' PHILIPPINES' 'NICARAGUA' 'CENTRAL PACIFIC' 'SOLOMON ISLANDS / VANUATU'
 'SOUTHWEST PACIFIC OCEAN' 'BAY OF BENGAL' 'MID-PACIFC OCEAN' 'SLOVENIA'
 'CURACAO' 'ICELAND' 'ITALY / CROATIA' 'BARBADOS' 'MONACO' 'GUYANA'
 'HAITI' 'SAN DOMINGO' 'KUWAIT' 'YEMEN ' 'FALKLAND ISLANDS' 'CRETE'
 'CYPRUS' 'EGYPT ' 'WEST INDIES' 'BURMA' 'LEBANON' 'PARAGUAY'
 'BRITISH NEW GUINEA' 'CEYLON' 'OCEAN' 'GEORGIA' 'SYRIA' 'TUVALU'
 'INDIAN OCEAN?' 'GUINEA' 'ANDAMAN ISLANDS' 'EQUATORIAL GUINEA / CAMEROON'
 'COOK ISLANDS' 'TOBAGO' 'PERU' 'AFRICA' 'ALGERIA' 'Coast of AFRICA'
 'TASMAN SEA' 'GHANA' 'GREENLAND' 'MEDITERRANEAN SEA' 'SWEDEN' 'ROATAN'
 'Between PORTUGAL & INDIA' 'DJIBOUTI' 'BAHREIN' 'KOREA' 'RED SEA?'
 'ASIA?' 'CEYLON (SRI LANKA)']
------------------------------
Valores únicos por columna: State
['NSW' 'Fredricksted Island St Croix' 'Kélé' 'California'
 'Sonoma County California' 'Hawaii West Coast Big Island'
 'Western Australia' 'Marquesas Islands' 'Hawaii' 'Texas' nan
 ' Bolivar, del Isolate' 'Queensland' 'South Australia' 'Off California'
 'Florida' 'Atlantic Ocean near Big Grand Cay' 'Carolina' 'Nuku Hiva'
 'Majorca' 'Fuerteventura' 'Great Abaco Islands' 'Massachusetts'
 'KwaZulu-Natal' 'Long Island NY' 'South Carolina' 'North Carolina'
 'South Santo' 'Montego Bay' 'Hadera' 'Quntana Roo' 'Kulhudhuffushi City'
 'WA' 'Victoria' 'Batangas Resort' 'Near five Cays settlement West Caicos'
 'Inhambane Province' 'Grande Terre' '?' 'North of Marsa Alam'
 'Phang Nga Province' 'Bay of Waitangi' 'Kaafu' 'Maui' 'Tela'
 'Timor Leste' 'Trujillo Colon' 'Southern Morocco' 'Gulf of Honduras'
 'Floria' 'Maahvah Laamu Atoll' 'Galveston' 'Providenciales Island'
 'Gambier Islands' 'Graet Courland Bay' 'Clarence Town Long Isand'
 'Nunu Atoll' 'Maharashtra' 'New  South Wales' 'Paradise Island'
 'Eastern Cape Province' 'Sonora' 'New South Wales' 'South Island'
 'Guerrero' 'New Providence   Isoad' 'Jalisco' 'Grand  Bahama Island'
 'Westerm Australia' 'North Island' 'Southern Red Sea' 'Quintana Roo'
 'Belize District' 'South Sinai' 'Bolinao' 'Valencia' 'Norte'
 "Savai'i island" 'New York' 'San Andrés Island' 'Galapagos Islands'
 'Red Sea Protectorate' 'Freeport' 'Tahiti' 'Poum'
 'Lucayan Lucayan Archipelago' ' Utah' 'New Jersey' 'Mayabeque'
 'Easten Cape Province' 'Artemisa' 'Pernambuco' 'Praslin Island'
 'South Province' 'Patagonia' 'Taveuni Island' 'Gulf of California'
 'Vaavu Atoll' 'KNZ' 'New South ales' 'Samoa' 'Louisiana' 'Mississippi'
 'Western  Australia' 'Western Cape Province' 'Cornwall' 'Noirth Carolina'
 'Okinawa' 'Bali' 'Hurghada, Red Sea Governorate' 'Ambergris Cay'
 'Bora Bora' 'Georgia' 'Phuket' 'Alabama' 'KZN' 'Isla De San Andres'
 'Guanacoste' 'Los Angeles' 'São Paulo.' 'Turks and Caicos' 'Nova Scotia'
 'Maryland' 'Chanthaburi Province' 'BAHAMAS' 'Galapagos' 'Aqaba'
 'West Sussex' 'Nouville' 'Ambergris Key' 'Westmoreland Parish'
 'Marquesas' 'Loyalty Islands' 'The Narrows' 'Raa Atoll' 'Oregon'
 ' Grand Bahama Island' 'Franklin County, Florida' 'Virgin Islands'
 'Tasmania' 'Tuamotu Islands' 'Maine' 'Bahamas' 'Exumas' 'Delaware'
 'Abaco Islands' 'Muang district of Satun province, ' 'Canary Islands'
 'Vanua Levu' 'Southland' 'Praslin' 'Central Province' 'Holquin' 'Moorea'
 'Baja ' 'Saint-Gilles' 'Guam' 'Northern Territory ' 'Cayman Islands'
 'Rhode Island' 'Chatham Islands' 'Quinta Roo' 'Lucayan Archipelago'
 'Bélep Islands' 'Noumea' 'Fernando de Noronha' 'Liaoning Province'
 'New South Wales ' 'Upolo' 'St. Marys Parish' 'County Cork'
 'Chieti, Province' 'Guizhou Province'
 'San Andres and Providencia Archipelago' 'The Exuma Cays' 'Colima'
 'Hua Hin' 'Cocos Island' 'Alifu Alifu Atoll' 'New Providence' 'Alagoas'
 'Boi Island, Victoria' 'Sepang' 'Holquin Province' 'Pamplemousses '
 ' Upolu Island' 'Shizuoka Prefecture' 'Castellón'
 'New Providence District' '40 miles off Grand Bahama Island'
 'Ascension Island' 'Washington' 'Tabasco' 'Anjouan' 'Ibiza Island'
 'South Devon' 'New Providence ' 'Sharjah, ' 'Baja California Sur'
 'Saint-Leu' 'Luzon Island' 'Tamaulipas' 'Saint-Andre' 'Bimini' 'Tuamotos'
 'North Province' 'New Providence Island' 'Alicante Province' 'Hong Kong'
 'Kochi Prefecture' 'Isla Providencia' 'Suez' 'Grand Terre'
 'Boa Vista Island' 'Santa Catarina State' 'Altagracia Province'
 'Grand Cayman' 'Balneário Camboriú' 'Fujairah Emirate'
 'Grand Canary Island' 'Alicante' 'Guanacaste' 'Grand Bahama Island'
 'Le Port' 'Rangiroa' 'Saint-Gilles-les-Bains' 'Sardinia' 'Sinaloa'
 'Central Tuamotu' 'd’Étang-Salé' 'Granada'
 'Cargados Carajos Shoals (St. Brandon)' 'Catalonia' 'West End'
 'Atsumi peninsula' 'Palmyra Atoll' 'Wallis and Futuna'
 'Baie de Sainte-Marie' 'Society Islands' 'Trinidad' 'Okinawa Prefecture'
 '740 miles SE of Tarawa Atoll' 'Southern District' 'Bay of Biscay'
 'Exuma Islands' 'Saint-Paul' 'Taitung ' 'Kingston Parish'
 'Santa Cruz Island' 'Tuamotus' 'Eleuthera' 'St. Catherine' 'Palawan'
 'Mercury Islands' 'Delta' "Vava'u" 'Inner Hebrides' 'Saint Leu'
 'Trois-Bassins' 'British Colombia' 'Saint-Benoit' 'Tabuk Province'
 'Antofagasta Province' "St John's" 'Santa Elena' 'East New Britain'
 'Bois-Blanc ' 'Moray' 'Puerto Rico' 'Samaná Province' 'Coast Province'
 'Primorsky Krai' 'Peter the Great Bay, Khasan, Primorsky Krai (Far East)'
 'Telyakovsky Bay, Khasan,  Primorsky Krai (Far East)' 'Sucre'
 'Middle Caicos' 'Caicos Bank' 'San Andrés archipelago' 'Kedah'
 'Umm al Qaywayan Province' 'Vitu Levu' 'South Sinai Peninsula'
 ' Loyalty Islands' 'Saint Gilles ' 'Virginia' "Ha'api "
 'Western Province' 'Jeju Province' 'Binh Dinh Province'
 'Antsiranana Province' 'Sinai Peninsula' 'Off Vanua Levu' 'Merizo'
 'Rio Grande Do Sul' 'Dubai' 'Torres Strait' 'Eastern Province'
 'Eastern Cape  Province' 'Maputo Province' 'Bocas' 'Fife' 'Devon'
 'Makira-Ulawa Province' 'Mombasa' 'Catalunya' 'St. Johns Reef'
 'Off Green Island' 'North Region' 'Batangas province' 'Strait of Malacca'
 'Guantanamo Province' 'Maranhão' 'Red Sea' 'Batanes Provine' 'Luzon'
 'Northern Territory' ' Split-Dalmatia Count,' 'North Devon'
 'US Virgin Islands' 'San Carlos' 'Cabo San Lucas' 'Sussex' 'Bahia'
 'Easter Ross' 'Guerro' 'Yasawa Islands' 'Northern Bahamas' 'Tokyo Bay'
 'Baja California' 'Green Bay' 'Marovo Lagoon'
 'Territory of Cocos (Keeling) Islands' 'Oslo Fjord' 'Kent' 'Bird Island'
 'Providenciales' 'Bimini Islands' 'Muhafazat Hadramawt' 'Cook islans'
 'Surigao del Norte' 'Between Somalia & Yemen' 'Ambergris Caye'
 'Saint-Pierre' 'Kentucky' 'Andros Islands' 'Western Area'
 '300 miles from Antigua' '800 miles from land'
 '600 nm west of the Canary Islands' 'Simpson Bay' 'East Wall'
 'Inner Islands' 'Shanghai' 'Malampa Province'
 "South Ch'ungch'ong Province" 'Bay Islands' 'New Mexico'
 'Santa Isabel Province' 'Santiago de Cuba Province' 'Camaguey Province'
 'Conservatória District' 'South Carolina ' 'Kuril Islands in the Pacific'
 'Wakayama Prefecture' "Nuku'alofa" 'Saint-Benoît'
 'South Island, near Karitane north of Dunedin' 'Rocha' 'Northlands'
 'Anzoategui' 'Cook Islands' 'Tamil Nadu' 'Pearl Islands' 'Taveuni'
 'Johnston Atoll' 'Baatan' 'Rio de Janeiro' 'Nueva Esparta'
 'North Pacific coast' 'Caroline Islands' 'Cheshire'
 'Louisiade Archipelago'
 'KwaZulu-Natal between Port Edward and Port St Johns'
 'Milne Bay Province' 'Cikobia Island (north of Vanua Levu)'
 'Rayong Province' 'Zamboanga del Sur Province' 'Rio Grande de Norte'
 'Off the western coast of peninsular Malaysia' 'New Brunswick'
 'Miyako Island' 'Alaska' 'Minerva Reef' 'Madang Province'
 'Worcestershire' 'Phang nga Province' 'Alinglaplap Atoll' 'Adriatic Sea'
 'Ralik Chain' 'Grand Baie' "L' Etang Salé-les-Bains" 'Southern Japan'
 'Cap Vert Peninsula' 'Marches region' 'Berry Islands' 'Transvaal' 'Gaza'
 "Grand'Anse" 'Beaufonds' 'Miyako' "L'Etang-Sale" 'Chatham Islands '
 'South Sinai, Gulf of Aqaba' 'Cat Cay' 'Missouri'
 '12 miles off the north coast' 'Saint-Paul '
 'Chatham Islands, east of New  Zealand' 'Saint-Denis' 'Vava’u'
 'Clearwater Bay' 'New Territories' 'Aichi Prefecture' 'Tafea Province'
 'Kagoshima Prefecture' 'Saint-Joseph' 'Banaadir Region' 'La Libertad'
 'Costa Blanca' 'Walkers Cay' 'On the Kowloon penisula, south of Sai Kung'
 'Ehime Prefecture' 'Tongapatu Group' 'West Africa' 'Wakaya Island'
 'North Carolina ' 'Mexico / Caribbean Sea' 'Antarctic Ocean'
 'La Saline-les-Bains' 'Sea of Japan' 'Tavenui' 'Ligurian Sea'
 "L'Etang-Salé" 'Kowloon Peninsula' 'Port Shelter' 'Laucala Island'
 'Sainte-Marie' 'Great Exuma Island' 'Sainte-Suzanne' 'Tuscany'
 'Tyrrhenian Sea' 'New Ireland' 'Valpariso Province' 'Viscayan Sea'
 'Manfredonia ' 'Tokyo Prefecture' 'Saint-Louis' 'Mindoro'
 'Between DR and Puerto Rico' 'Between Honiara & Isabel Island'
 'Florida Straits' 'Gulf of Lyons' 'Cádiz' 'Sicily' 'Andikira Fokithes'
 'Central Philippines' 'Northwest Italy' 'English Channel'
 'North & South Carolina' 'Carolina coast' 'Kumamoto Prefecture' 'Biserta'
 'Saint-Philippe' 'Chungnam' 'Eronogo Region' 'Coquimbo'
 'Pagasitikos Gulf' "St. Mary's Parish" 'Romblon Province'
 'Lamu Archipelago' 'Los Vilos' 'Island of Kos' "Ha'api" 'Madeira Islands'
 'Ho Ha Wan Marine Park' 'Southern Thailand' 'Golfo de Venezia'
 'Ralik Archipelago' 'South China Sea 200 miles from Hong Kong'
 'Reggio Calabria Province' 'Mirs Bay ' 'Genoa Province'
 'Ganges-Brahmaputra delta' ' Split-Dalmatia County' 'Florida '
 'Primorje-Gorski Kotar County ' 'Aulong Island'
 'Western Caroline Islands' 'Upolu Island' 'Antibes' 'Illeginni Atoll'
 'Istria County' 'Between Beira & Maputo' 'Istria ' 'Khuzestan Province'
 'Inhambe Province' 'Namonuito Atoll' 'Eastern Caroline Islands'
 'Western Caroline Islands (North Pacific Ocean)' 'Caribbean Sea'
 'St. Andrew Parish' '200 nm southeast of Manila' 'Limpopo River'
 'New Ireland Province' 'Zadar County' 'Basrah' 'Clarendon' 'Moro Gulf'
 'Johor' 'Magdalena Department' 'Mafia Island' 'Gulf Province'
 'Morobe Province' 'Limón Province' 'Rombion Province' 'Veracruz'
 'Brindisi Province' 'Kagawa Prefecture' 'Liguria' 'Hamilton'
 'Out Islands' 'Mugla Province' 'Gibraltar' 'New Britain' 'Bay of Maputo'
 'Duke of York Islands' 'Taranto province' 'Northern Taiwan'
 'Admiralty Islands, Manus Province' 'North Sumatra'
 "250 miles southwest of O'ahu, Hawaii" 'West coast' 'East Sepik'
 'Near Bougainville (North Solomons)' 'East of the Gulf of Aqaba'
 'Bougainville (North Solomons)' 'Victoria ' 'Okayama Prefecture'
 'San Blas' 'Connecticut' 'Lau Group' 'Caribbean Coast' 'Vita Levu'
 'San Blas Islands' 'Puntarenas Province' 'Lomaloma, Lau'
 'Between Southampton & Canary Islands' 'South Coast, East New Britain'
 ' Lau Province' 'Ysabel Island' 'Santo Domingo' 'San Blas coast'
 'Thessaly' 'Lomaiviti  Island Group' 'Rodrigues' 'Manus Island'
 'Pinas Bay' 'Grand Turk Island' 'Off coast of West Africa' 'Sharon'
 'Antalya Province' 'Northern District'
 'New Ireland Province, Bismarck Archipelago' 'Cyclades' 'Viti Levu'
 'Off the Coromandel Peninsula, North Island' 'Madang'
 'Guadalcanal Province' '10ºS, 142ºE' 'Kwajalein Atoll' 'East Flores'
 'Guerrrero' 'Western Luzon Island' 'Shefa Province'
 '165  miles from Bermuda'
 '25 km off the coast of Iran & 483km from mouth of Persian Gulf'
 'Venice Province' 'Sandaun Province' 'Anatolia'
 'East New Britain Province' 'United Arab Emirates'
 'Wake Island (EnenKio)' '19S, 178?E' 'Pennsylvania' '9.35N 79.35W'
 'Roncador Bank' 'Western District' 'Enroute from Suez to Aden (Yemen)'
 '180 miles southeast of Okinawa' 'Eniwetok Atoll' 'Cap-Vert Peninsula'
 'Delagoa Bay' 'In the English Channel ' 'Cook Strait'
 'Unknown, treated at Wick, SCOTLAND' 'Corregidor Island' 'Paget'
 '33N, 68W' 'Casamance' 'Madang (WO)' 'Between Timor & Darwin, Australia'
 'Pacific coast' 'St. Georges ' 'Eastern  Province'
 'Northwest of Viti Levu' 'West New Britain Province' 'Rigo subdistrict'
 'Masbate' '400 miles southeast of Sri Lanka' 'Lomaiviti Province'
 'Kadavu' 'Leyte Island' 'Orissa' 'Hokkaido Prefecture' 'North Palawan'
 'Queaon' 'Istria' 'PANAMA' 'In the Gulf Stream ' 'Mersin Province'
 'Guyamas' 'Between England & South Africa' 'Mindanao'
 ' Kikori River mouth' 'South Chungcheong Province' 'Ahirkapi coast'
 'Tutuila Island' 'Primorje-Gorski Kotar County'
 'Between Hawaii & Wake Island' 'Taipei Hsien' 'Ibaraki Prefecture'
 'South Pacific Ocean' 'Canal Zone' '1,000 miles east of Hawaii' 'Honiara'
 'Yucatan Channel' 'Havana Province' 'Karun River'
 'Abau Subdistrict,Central Province' 'New Britain, Bismarck Archipelago'
 'Estuaire Province' 'Near Dakar, Cap Vert Peninsula'
 'Near the Andaman & Nicobar Islands' 'Mozambique Channel' 'Tyrrenian Sea'
 'Congreve Channel' 'St. Thomas Bay' 'Madeira'
 'Between Comores & Madagascar' 'Corfu Island' '1000 miles west of Hawaii'
 'Izo Islands' ' Primorje-Gorski Kotar County' 'Open sea' 'Aden'
 'New Ireland, Bismarck Archipelago' '18S / 50E' 'Illinois'
 'Isles del Rosario' 'Wake Island' 'Isle of Man' 'Nagasaki Prefecture'
 'Liguaria' 'Slovenia' 'South shore ' 'Buenos Aires Province'
 '330 to 350 miles east of Wake Island' 'Gulf of Panama' 'Genoa  Province'
 'Abau Sub District, Central Province' 'Teramo' 'Red Sea State' 'Curacao'
 'Port Louis Province' 'Montserrado' 'Bay of Maputu' 'Sofala Province'
 'Salerno' 'Salerno Province' 'Taranto' 'Naples Province' ' La Libertad'
 'Sago Prefecture' 'Savona' 'Southern Province' 'Jakarta Harbour'
 'Singapore Harbor' 'Calabria' 'Shatt-el-Arab River' 'Shatt-al-Arab River'
 'Calvados Archipelago' 'Shat-Al-Arab River'
 'Between Kwajalein Atoll & Johnston Island' 'Attica' 'Adana Province'
 'Bandar Ma’shur sea inlet' 'Saipan' 'Carpathian Sea' 'Kwajalein'
 'Dar-es-Salaam ' '"Head of the Gulf"' 'Ryukyu' ' North Carolina'
 'In transit between Tinian and Leyte' 'Northern Java' 'Tel Aviv'
 'Colon Province' '300 miles east of Luzon'
 'Bernardino Strait near Gulf of Leyte'
 'Off Samar Island in the Gulf of Leyte' 'Lake Nicaragua (fresh water)'
 'Pacific Ocean' 'Near the Fiji Islands' '40 miles south of Naples '
 'Northwest of Papua New Guinea' 'Between Hawaii and U.S.A.'
 'Off South American coast' 'Makora-Ulawa Province' '04.05N-13.23W'
 'Midway Atoll' '300 miles east of St. Thomas (Virgin Islands)'
 'West of Ceylon (Sri  Lanka)' 'East Java' 'Camiguin Island'
 'Cay Sal Bank' '(Southwestern Pacific)' 'Panama City' 'Off Libya'
 'North of Pernambuco, Brazil' 'Off coast of Ecuador' 'Trelawney Province'
 'In Convoy OB 274' 'New Georgia' 'Panama Bay (Pacific Ocean)' 'Bwagaoia'
 'Western Papuan Gulf' 'Torres Strait ' 'Carabobo' 'Ascension Bay'
 'North China' 'Lower San Juan River' 'Nicoya Peninsula' 'Basrah City'
 'West Bengal' 'Queensland ' 'Argyllshire' 'Arran' 'Argyll'
 'Fishing Grounds' 'Newfoundland' 'Isle of Wight' 'Makira-Uluwa Province'
 'Northern (Oro) Province' 'Herzliyah' 'Elqui Province' 'Istanbul'
 'St Michael Parish' 'Barlavento Islands' 'Viti Levu Island'
 'Bay of Fundy' 'Manila' 'French Southern Territories' 'Niua '
 'Black River' 'Phoenix Islands' 'Cienfuegos Province' 'Santiago Island'
 'Near Puntarenas' 'Porto Seguro' 'Salinas Bay'
 'Golfo di Genova in the Ligurian Sea' 'Sants-Montjic'
 'South of the Equator ' 'Bay of Monaco' 'Valencia ' 'Vancouver'
 '2 to 3 miles off Taboguilla Island, Pacific Ocean' 'Dorset'
 '150 miles offshore' 'Galica' 'Demerara County' 'Vera Cruz' ' Manila Bay'
 'Lucy' 'East Yorkshire' 'Cavite Province, Luzon' 'Cape Haitien' 'Leyte'
 'Halifax' 'Turtle Bogue'

In [20]:
Shark_Attacks_df['Fatal Y/N'].unique()

array(['N', 'Y', 'F', 'M', nan, 'n', 'Nq', 'UNKNOWN', 2017, 'Y x 2', ' N',
       'N ', 'y'], dtype=object)

In [17]:
print(f"El dataset tiene {Shark_Attacks_df.shape[0]} filas y {Shark_Attacks_df.shape[1]} columnas.")
print(Shark_Attacks_df.columns)

El dataset tiene 7065 filas y 23 columnas.
Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [24]:
Ataques_por_pais = Shark_Attacks_df["Country"].value_counts()
Ataques_por_pais

Country
USA                   2578
AUSTRALIA             1482
SOUTH AFRICA           597
NEW ZEALAND            144
PAPUA NEW GUINEA       136
                      ...
GRAND CAYMAN             1
ST. MAARTIN              1
US Virgin Islands        1
GULF OF ADEN             1
CEYLON (SRI LANKA)       1
Name: count, Length: 251, dtype: int64

In [25]:
Shark_Attacks_df.describe()

              Year  original order
count  7063.000000     6799.000000
mean   1935.890981     3401.152081
std     270.825801     1963.076319
min       0.000000        2.000000
25%    1948.000000     1701.500000
50%    1986.000000     3401.000000
75%    2010.000000     5100.500000
max    2026.000000     6802.000000